# Generated by Django 4.0.1 on 2022-03-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contaRazao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeContaRazao', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='tipoMovimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nometipoMovimento', models.CharField(max_length=20)),
            ],
        ),
    ]
