# Generated by Django 4.0.1 on 2022-03-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contarazao_tipomovimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipoOrdem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeTipoOrdem', models.CharField(max_length=20)),
            ],
        ),
    ]
