# Generated by Django 4.0.1 on 2022-03-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_localinstal'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipoAtv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nometipoAtv', models.CharField(max_length=20)),
            ],
        ),
    ]
