# Generated by Django 4.0.1 on 2022-03-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_responsavel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeProduto', models.CharField(max_length=20)),
                ('partNumber', models.IntegerField(max_length=10)),
                ('CentroCusto', models.CharField(max_length=4)),
                ('descri', models.CharField(max_length=50)),
            ],
        ),
    ]
