# Generated by Django 4.0.1 on 2022-03-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='nivelAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeAcesso', models.CharField(max_length=20)),
            ],
        ),
    ]
