# Generated by Django 4.0.1 on 2022-03-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_nivelacesso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='partNumber',
            field=models.IntegerField(),
        ),
    ]
