# Generated by Django 4.0.3 on 2022-03-16 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_fotosproduto'),
    ]

    operations = [
        migrations.CreateModel(
            name='divisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeDivisao', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TransacaoSucata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=100)),
                ('txtBreve', models.CharField(max_length=20)),
                ('trab', models.DecimalField(decimal_places=2, max_digits=5)),
                ('un', models.CharField(max_length=2)),
                ('idtipoOrdemFK', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_ordem', to='home.tipoordem')),
            ],
        ),
    ]
