# Generated by Django 4.0.3 on 2022-03-16 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_divisao_transacaosucata'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacaosucata',
            name='idLocalFK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='localInstal', to='home.localinstal'),
        ),
        migrations.AddField(
            model_name='transacaosucata',
            name='idPrioridadeFK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prioridade', to='home.prioridade'),
        ),
    ]
