# Generated by Django 4.0.3 on 2022-03-16 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_transacaosucata_idlocalfk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacaosucata',
            name='idtipoavtFK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipoAtv', to='home.tipoatv'),
        ),
    ]
