# Generated by Django 4.0.3 on 2022-03-16 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_transacaosucata_idtipoavtfk'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacaosucata',
            name='idCenTrabFK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CentralTrab', to='home.centraltrab'),
        ),
        migrations.AddField(
            model_name='transacaosucata',
            name='iddivisaoFK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='divisao', to='home.divisao'),
        ),
    ]
