# Generated by Django 4.0.3 on 2022-03-16 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_transacaosucata_idcentrabfk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacaosucata',
            name='idCentroCustoFK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='centroCusto', to='home.centrocusto'),
        ),
    ]
