# Generated by Django 4.0.3 on 2022-03-16 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_transacaosucata_idcentrocustofk'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransacaoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recebedor', models.CharField(max_length=15)),
                ('material', models.CharField(max_length=50)),
                ('idContaRazaoFK', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contaRazao', to='home.contarazao')),
                ('idProdutoFK', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Produto', to='home.produto')),
                ('idTipoMovimentoFK', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipoMovimento', to='home.tipomovimento')),
            ],
        ),
    ]
