# Generated by Django 4.0.3 on 2022-03-16 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_transacaoproduto_dep_transacaoproduto_idcentrocfk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edv', models.IntegerField()),
                ('senha', models.CharField(max_length=20)),
                ('idNivelAcessFK', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.nivelacesso')),
                ('idRespFK', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.responsavel')),
            ],
        ),
    ]
