# Generated by Django 4.0.3 on 2022-03-16 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_historicosucata'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('idTraProdutoFK', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.transacaoproduto')),
                ('idUserFK', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.usuario')),
            ],
        ),
    ]
