# Generated by Django 4.0.1 on 2022-03-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_historicoproduto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centrocusto',
            name='nomeCentro',
        ),
        migrations.AddField(
            model_name='centrocusto',
            name='codigoCentro',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
