# Generated by Django 4.0.3 on 2022-03-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_remove_centrocusto_nomecentro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='descri',
            field=models.CharField(max_length=100),
        ),
    ]
