# Generated by Django 4.0.3 on 2022-03-22 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_produto_descri'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FotosProduto',
            new_name='Fotos',
        ),
    ]
