# Generated by Django 4.0.3 on 2022-03-23 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_rename_fotosproduto_fotos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotos',
            name='nomeProduto',
        ),
    ]
