# Generated by Django 4.0.3 on 2022-03-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_rename_iduserfk_historicoproduto_idusuariofk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='edv',
            field=models.BigIntegerField(),
        ),
    ]
