# Generated by Django 4.0.3 on 2022-03-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_alter_usuario_edv'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.CharField(default=0, max_length=80),
            preserve_default=False,
        ),
    ]
