# Generated by Django 4.0.3 on 2022-04-02 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_usuario_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='codigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='transacaosucata',
            name='idCenTrabFK',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CentralTrab', to='home.centraltrab'),
        ),
        migrations.AlterField(
            model_name='transacaosucata',
            name='idCentroCustoFK',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='centroCusto', to='home.centrocusto'),
        ),
        migrations.AlterField(
            model_name='transacaosucata',
            name='idLocalFK',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='localInstal', to='home.localinstal'),
        ),
        migrations.AlterField(
            model_name='transacaosucata',
            name='idPrioridadeFK',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prioridade', to='home.prioridade'),
        ),
        migrations.AlterField(
            model_name='transacaosucata',
            name='iddivisaoFK',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='divisao', to='home.divisao'),
        ),
        migrations.AlterField(
            model_name='transacaosucata',
            name='idtipoOrdemFK',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_ordem', to='home.tipoordem'),
        ),
        migrations.AlterField(
            model_name='transacaosucata',
            name='idtipoavtFK',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipoAtv', to='home.tipoatv'),
        ),
        migrations.AlterField(
            model_name='transacaosucata',
            name='un',
            field=models.CharField(blank=True, default='H', max_length=2, null=True),
        ),
    ]
